### ISSUE TITLE
ValueError and TypeError

### ISSUE THREAD

**Issue by nanxintin** [ebonyclock/deep_rl_vizdoom#1]
Hi @ebonyclock ,
Thank you for sharing the code.
I have focused on ViZDoom research several weeks, and I found the repository recently.
When I tried to run the code python3 train_dqn.py, I came across some errors.
'''
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 436, in apply_op
    as_ref=input_arg.is_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 777, in internal_convert_n_to_tensor
    preferred_dtype=preferred_dtype))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 716, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 589, in _TensorTensorConversionFunction
    % (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype int32 for Tensor with dtype int64: 'Tensor("ArgMax:0", shape=(?,), dtype=int64)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_dqn.py", line 25, in <module>
    dqn = DQN(**dqn_settings)
  File "/home/sk/drl/deep_rl_vizdoom/dqn.py", line 58, in __init__
    **settings)
  File "/home/sk/drl/deep_rl_vizdoom/networks/dqn.py", line 133, in __init__
    super(DuelingDQNNet, self).__init__(*args, **kwargs)
  File "/home/sk/drl/deep_rl_vizdoom/networks/dqn.py", line 56, in __init__
    self._prepare_ops()
  File "/home/sk/drl/deep_rl_vizdoom/networks/dqn.py", line 72, in _prepare_ops
    best_q2 = gather_2d(q2_frozen, best_a2)
  File "/home/sk/drl/deep_rl_vizdoom/util/tfutil.py", line 8, in gather_2d
    return tf.gather_nd(tensor_2d, tf.stack([tf.range(tf.shape(tensor_2d)[0]), col_indices], 1))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 842, in stack
    return gen_array_ops._pack(values, axis=axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 2041, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 464, in apply_op
    raise TypeError("%s that don't all match." % prefix)
TypeError: Tensors in list passed to 'values' of 'Pack' Op have types [int32, int64] that don't all match.
'''
I have fixed some errors in tf.concat() to fit the TF1.0, and still can't run train_dqn.py and train_async.py successfully.
Could you give some advice on running your code?
Thanks again.

**Comment by ebonyclock** [comment]
Hi @nanxintin, thanks for interest. I must have migrated the code to tf 0.12.1 instead of 1.0. After latest commits it should be ok and running ./train_dqn.py or ./train_async.py should work. However, default settings are quite arbitrary so out-of-the-box good results should not be expected (use -s switch to add settings file in yamls like the ones in settings dir). I will try to add some descriptions and ready examples soon. Thank for motivation.

**Comment by nanxintin** [comment]
Hi @ebonyclock ,
Thanks for your reply.
Looking for your descriptions and examples on this work.

**Comment by ebonyclock** [comment]
@nanxintin Wow, that was a quick reaction to update. Sorry it took me so long to do anything.
