### ISSUE TITLE
How can I test the model trained with A3C?

### ISSUE THREAD

**Issue by GoingMyWay** [ebonyclock/deep_rl_vizdoom#5]
Hi @ebonyclock , I wanna train an agent in health_grathering scenario with A3C algorithm, to train it

 `python3 train_a3c.py -s settings/health_gathering.yml`

with `a3c_defaults.yml` settings.

and to test it

`./test_a3c.py models/07.18_12-39/ACLstmNet  -s   settings/defaults/a3c_defaults.yml    settings/health_gathering.yml`

But it doesn't work, it reported the following error

```
Loading common default settings from: settings/defaults/common_defaults.yml
Loading default settings from: settings/defaults/adqn_defaults.yml
Loading settings from: settings/defaults/a3c_defaults.yml
/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/ruamel/yaml/constructor.py:260: DuplicateKeyFutureWarning: while constructing a mapping
  in "settings/defaults/a3c_defaults.yml", line 1, column 1
found duplicate key "learning_rate_decay_steps" with value "10000000.0" (original value: "10000000.0")
  in "settings/defaults/a3c_defaults.yml", line 22, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become and error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
Loading settings from: settings/health_gathering.yml
Loaded settings.
Loaded settings.
Traceback (most recent call last):
  File "./test_a3c.py", line 7, in <module>
    test_a3c()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_train_test.py", line 115, in test_a3c
    test_async(q_learning=False, settings=settings, modelfile=args.model, eps=args.episodes_num)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_async_algo.py", line 93, in test_async
    agent = A3CLearner(thread_index=0, session=session, **settings)
TypeError: __init__() missing 1 required positional argument: 'global_steps_counter'
```

And I added the following code in `test_async` function

```
    global_steps_counter = ThreadsafeCounter()
    global_step = tf.Variable(0, name='global_step', trainable=False)

    if q_learning:
        agent = ADQNLearner(thread_index=0, session=session, **settings)
    else:
        agent = A3CLearner(global_steps_counter=global_steps_counter, thread_index=0, session=session, **settings)
```

It reported the following error:

```
Loading common default settings from: settings/defaults/common_defaults.yml
Loading default settings from: settings/defaults/adqn_defaults.yml
Loading settings from: settings/defaults/a3c_defaults.yml
/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/ruamel/yaml/constructor.py:260: DuplicateKeyFutureWarning: while constructing a mapping
  in "settings/defaults/a3c_defaults.yml", line 1, column 1
found duplicate key "learning_rate_decay_steps" with value "10000000.0" (original value: "10000000.0")
  in "settings/defaults/a3c_defaults.yml", line 22, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become and error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
Loading settings from: settings/health_gathering.yml
Loaded settings.
Loaded settings.
Creating actor-learner #0.
Initializing variables...
Initialization finished.

Loading model from: models/07.18_12-39/ACLstmNet
INFO:tensorflow:Restoring parameters from models/07.18_12-39/ACLstmNet
Restoring parameters from models/07.18_12-39/ACLstmNet
Loaded model.

Scores: 
Traceback (most recent call last):
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: lstm_ac_0/conv0/convolution = Conv2D[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 4, 4], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_state_img_0_3, lstm_ac_0/conv0/weights/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test_a3c.py", line 7, in <module>
    test_a3c()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_train_test.py", line 115, in test_a3c
    test_async(q_learning=False, settings=settings, modelfile=args.model, eps=args.episodes_num)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_async_algo.py", line 105, in test_async
    reward = agent.run_episode(deterministic=deterministic)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/async_learner.py", line 203, in run_episode
    action_index = self._get_best_action(self._session, current_state, deterministic=deterministic)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/async_learner.py", line 327, in _get_best_action
    policy = self.local_network.get_policy(sess, state)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 191, in get_policy
    feed_dict=self.get_standard_feed_dict(state))
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnimplementedError: Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: lstm_ac_0/conv0/convolution = Conv2D[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 4, 4], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_state_img_0_3, lstm_ac_0/conv0/weights/read)]]

Caused by op 'lstm_ac_0/conv0/convolution', defined at:
  File "./test_a3c.py", line 7, in <module>
    test_a3c()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_train_test.py", line 115, in test_a3c
    test_async(q_learning=False, settings=settings, modelfile=args.model, eps=args.episodes_num)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_async_algo.py", line 93, in test_async
    agent = A3CLearner(global_steps_counter=global_steps_counter, thread_index=0, session=session, **settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/async_learner.py", line 88, in __init__
    thread=thread_index, **settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 229, in __init__
    super(ACLstmNet, self).__init__(**settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 139, in __init__
    super(_BaseACRecurrentNet, self).__init__(**settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 36, in __init__
    self.ops.pi, self.ops.v = self.create_architecture()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 147, in create_architecture
    fc_input = self.get_input_layers()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/common.py", line 68, in get_input_layers
    self.conv_strides)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/common.py", line 19, in create_conv_layers
    padding="VALID", scope=name_scope + "/conv" + str(i))
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 947, in convolution
    outputs = layer.apply(inputs)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/layers/convolutional.py", line 158, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

UnimplementedError (see above for traceback): Generic conv implementation only supports NHWC tensor format for now.
	 [[Node: lstm_ac_0/conv0/convolution = Conv2D[T=DT_FLOAT, data_format="NCHW", padding="VALID", strides=[1, 1, 4, 4], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_state_img_0_3, lstm_ac_0/conv0/weights/read)]]
```

I trained the model on a GPU server and run the test code on my Mac.

And I found that "NCHW" data format has not been implemented on CPU and I removed "NCHW" . And then it reported the following error

```
Loading common default settings from: settings/defaults/common_defaults.yml
Loading default settings from: settings/defaults/adqn_defaults.yml
Loading settings from: settings/defaults/a3c_defaults.yml
/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/ruamel/yaml/constructor.py:260: DuplicateKeyFutureWarning: while constructing a mapping
  in "settings/defaults/a3c_defaults.yml", line 1, column 1
found duplicate key "learning_rate_decay_steps" with value "10000000.0" (original value: "10000000.0")
  in "settings/defaults/a3c_defaults.yml", line 22, column 1

To suppress this check see:
    http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become and error in future releases, and are errors
by default when using the new API.

  warnings.warn(DuplicateKeyFutureWarning(*args))
Loading settings from: settings/health_gathering.yml
Loaded settings.
Loaded settings.
Creating actor-learner #0.
Traceback (most recent call last):
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/common_shapes.py", line 671, in _call_cpp_shape_fn_impl
    input_tensors_as_shapes, status)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 8 from 4 for 'lstm_ac_0/conv0/convolution' (op: 'Conv2D') with input shapes: [?,4,60,80], [8,8,80,32].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test_a3c.py", line 7, in <module>
    test_a3c()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_train_test.py", line 115, in test_a3c
    test_async(q_learning=False, settings=settings, modelfile=args.model, eps=args.episodes_num)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/_async_algo.py", line 93, in test_async
    agent = A3CLearner(global_steps_counter=global_steps_counter, thread_index=0, session=session, **settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/async_learner.py", line 88, in __init__
    thread=thread_index, **settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 229, in __init__
    super(ACLstmNet, self).__init__(**settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 139, in __init__
    super(_BaseACRecurrentNet, self).__init__(**settings)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 36, in __init__
    self.ops.pi, self.ops.v = self.create_architecture()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/a3c.py", line 147, in create_architecture
    fc_input = self.get_input_layers()
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/common.py", line 68, in get_input_layers
    self.conv_strides)
  File "/Users/qiuwei/Research/ReinforceLearning/Github/deep_rl_vizdoom/networks/common.py", line 19, in create_conv_layers
    padding="VALID", scope=name_scope + "/conv" + str(i))
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 181, in func_with_args
    return func(*args, **current_args)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 947, in convolution
    outputs = layer.apply(inputs)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/layers/base.py", line 492, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/layers/base.py", line 441, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/layers/convolutional.py", line 158, in call
    data_format=utils.convert_data_format(self.data_format, self.rank + 2))
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 670, in convolution
    op=op)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 338, in with_space_to_batch
    return op(input, num_spatial_dims, padding)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 662, in op
    name=name)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/nn_ops.py", line 131, in _non_atrous_convolution
    name=name)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 399, in conv2d
    data_format=data_format, name=name)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/Users/qiuwei/Library/Python/3.6/lib/python/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Negative dimension size caused by subtracting 8 from 4 for 'lstm_ac_0/conv0/convolution' (op: 'Conv2D') with input shapes: [?,4,60,80], [8,8,80,32].
```

Hope you can help, thanks!

**Comment by GoingMyWay** [comment]
I solved this issue! Thank you!

**Comment by ebonyclock** [comment]
As for the problem with global step counter I have removed the need for it.

Regarding the "NCHW', I was aware that and treated it partly as a failsafe to check if gpu is properly setup. Maybe it's a better idea to make it configurable or add it to script args.
